apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
     variables_order = "EGPCS"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-app
  labels:
    app: lamp-app
spec:
  selector:
    matchLabels:
      app: lamp-app
  template:
    metadata:
      name: php-pod
      labels:
        app: lamp-app
    spec:
      containers:
        - name: php-container
          image: webdevops/php-apache:alpine-3-php7
          resources: {}
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: database
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: database
                key: MYSQL_USER
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: database
                key: MYSQL_HOST
          volumeMounts:
          - name: php-ini
            mountPath: /opt/docker/etc/php/php.ini
            subPath: php.ini
      volumes:
      - name: php-ini
        configMap:
          name: php-config